// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackendDSBot.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BannedServiceDbContext))]
    partial class BannedServiceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Persistence.Entities.BotJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DedupKey")
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discord_user_id");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_at");

                    b.Property<string>("LockedBy")
                        .HasColumnType("text")
                        .HasColumnName("locked_by");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("RunAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_after");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("LockedAt")
                        .HasDatabaseName("ix_bot_jobs_locked_at");

                    b.HasIndex("Type", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_bot_jobs_type_dedup_key")
                        .HasFilter("\"dedup_key\" IS NOT NULL");

                    b.HasIndex("Status", "RunAfter", "CreatedAt")
                        .HasDatabaseName("ix_bot_jobs_status_runafter_createdat");

                    b.ToTable("bot_jobs", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.ConfigEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("BanRouletteDurationMaxSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("ban_roulette_duration_max_seconds");

                    b.Property<int>("BanRouletteDurationMinSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("ban_roulette_duration_min_seconds");

                    b.Property<int>("BanRouletteIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("ban_roulette_interval_seconds");

                    b.Property<int>("BanRoulettePickCount")
                        .HasColumnType("integer")
                        .HasColumnName("ban_roulette_pick_count");

                    b.Property<string>("EligibleRoleId")
                        .HasColumnType("text")
                        .HasColumnName("eligible_role_id");

                    b.Property<string>("JailVoiceChannelId")
                        .HasColumnType("text")
                        .HasColumnName("jail_voice_channel_id");

                    b.Property<int>("TicketRouletteIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_roulette_interval_seconds");

                    b.Property<int>("TicketRoulettePickCount")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_roulette_pick_count");

                    b.Property<int>("TicketRouletteTicketsMax")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_roulette_tickets_max");

                    b.Property<int>("TicketRouletteTicketsMin")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_roulette_tickets_min");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("config", null, t =>
                        {
                            t.HasCheckConstraint("ck_config_single_row", "\"id\" = 1");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.EligibleUserEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discord_user_id");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<bool>("IsEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_eligible");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_eligible_users_snapshot_guild_discord");

                    b.HasIndex("GuildId", "IsEligible")
                        .HasDatabaseName("ix_eligible_users_snapshot_guild_eligible");

                    b.ToTable("eligible_users_snapshot", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PunishmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<string>("GuildId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guild_id");

                    b.Property<int>("PriceTickets")
                        .HasColumnType("integer")
                        .HasColumnName("price_tickets");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "GuildId")
                        .IsUnique()
                        .HasDatabaseName("ux_punishments_active_user_guild")
                        .HasFilter("\"status\" = 'Active'");

                    b.HasIndex("GuildId", "Status", "EndsAt")
                        .HasDatabaseName("ix_punishments_guild_status_endsat");

                    b.ToTable("punishments", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PunishmentHistoryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("DeltaSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("delta_seconds");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<Guid>("PunishmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("punishment_id");

                    b.HasKey("Id");

                    b.HasIndex("PunishmentId")
                        .HasDatabaseName("ix_punishment_history_punishment_id");

                    b.ToTable("punishment_history", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.RouletteRoundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("Type", "StartedAt")
                        .HasDatabaseName("ix_roulette_rounds_type_started_at");

                    b.ToTable("roulette_rounds", (string)null);
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.TicketTransferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("FromUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_user_id");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_user_id");

                    b.HasKey("Id");

                    b.HasIndex("FromUserId")
                        .HasDatabaseName("ix_ticket_transfers_from_user_id");

                    b.HasIndex("ToUserId")
                        .HasDatabaseName("ix_ticket_transfers_to_user_id");

                    b.ToTable("ticket_transfers", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_transfers_amount_positive", "\"amount\" > 0");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("discord_user_id");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("TicketsBalance")
                        .HasColumnType("integer")
                        .HasColumnName("tickets_balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("ux_users_discord_user_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_tickets_balance_nonnegative", "\"tickets_balance\" >= 0");
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PunishmentEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infrastructure.Persistence.Entities.PunishmentHistoryEntity", b =>
                {
                    b.HasOne("Infrastructure.Persistence.Entities.PunishmentEntity", "Punishment")
                        .WithMany()
                        .HasForeignKey("PunishmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Punishment");
                });
#pragma warning restore 612, 618
        }
    }
}
